final Map<String, int> postCategories = {
  "AYUSH": 0,
  "Cabinet": 0,
  "Cabinet Committee Decisions": 0,
  "Cabinet Committee on Economic Affairs (CCEA)": 0,
  "Cabinet Committee on Infrastructure": 0,
  "Cabinet Committee on Investment": 0,
  "Cabinet Committee on Price": 0,
  "Cabinet Secretariat": 0,
  "Competition Commission of India": 0,
  "Department of Atomic Energy": 0,
  "Department of Ocean Development": 0,
  "Department of Space": 0,
  "EAC-PM": 0,
  "Election Commission": 0,
  "Finance Commission": 0,
  "IFSC Authority": 0,
  "Lok Sabha Secretariat": 0,
  "Lokpal of India": 0,
  "Ministry of AYUSH": 0,
  "Ministry of Agriculture & Farmers Welfare": 0,
  "Ministry of Agro & Rural Industries": 0,
  "Ministry of Chemicals and Fertilizers": 0,
  "Ministry of Civil Aviation": 0,
  "Ministry of Coal": 0,
  "Ministry of Commerce & Industry": 0,
  "Ministry of Communications": 0,
  "Ministry of Company Affairs": 0,
  "Ministry of Consumer Affairs, Food & Public Distribution": 0,
  "Ministry of Cooperation": 0,
  "Ministry of Corporate Affairs": 0,
  "Ministry of Culture": 0,
  "Ministry of Defence": 0,
  "Ministry of Development of North-East Region": 0,
  "Ministry of Disinvestment": 0,
  "Ministry of Drinking Water & Sanitation": 0,
  "Ministry of Earth Sciences": 0,
  "Ministry of Education": 0,
  "Ministry of Electronics & IT": 0,
  "Ministry of Environment, Forest and Climate Change": 0,
  "Ministry of External Affairs": 0,
  "Ministry of Finance": 0,
  "Ministry of Fisheries, Animal Husbandry & Dairying": 0,
  "Ministry of Food Processing Industries": 0,
  "Ministry of Health and Family Welfare": 0,
  "Ministry of Heavy Industries": 0,
  "Ministry of Home Affairs": 0,
  "Ministry of Housing & Urban Affairs": 0,
  "Ministry of Information & Broadcasting": 0,
  "Ministry of Jal Shakti": 0,
  "Ministry of Labour & Employment": 0,
  "Ministry of Law and Justice": 0,
  "Ministry of Micro, Small & Medium Enterprises": 0,
  "Ministry of Mines": 0,
  "Ministry of Minority Affairs": 0,
  "Ministry of New and Renewable Energy": 0,
  "Ministry of Overseas Indian Affairs": 0,
  "Ministry of Panchayati Raj": 0,
  "Ministry of Parliamentary Affairs": 0,
  "Ministry of Personnel, Public Grievances & Pensions": 0,
  "Ministry of Petroleum & Natural Gas": 0,
  "Ministry of Planning": 0,
  "Ministry of Ports, Shipping and Waterways": 0,
  "Ministry of Power": 0,
  "Ministry of Railways": 0,
  "Ministry of Road Transport & Highways": 0,
  "Ministry of Rural Development": 0,
  "Ministry of Science & Technology": 0,
  "Ministry of Skill Development and Entrepreneurship": 0,
  "Ministry of Social Justice & Empowerment": 0,
  "Ministry of Statistics & Programme Implementation": 0,
  "Ministry of Steel": 0,
  "Ministry of Surface Transport": 0,
  "Ministry of Textiles": 0,
  "Ministry of Tourism": 0,
  "Ministry of Tribal Affairs": 0,
  "Ministry of Urban Development": 0,
  "Ministry of Water Resources, River Development and Ganga Rejuvenation": 0,
  "Ministry of Women and Child Development": 0,
  "Ministry of Youth Affairs and Sports": 0,
  "NITI Aayog": 0,
  "National Financial Reporting Authority": 0,
  "National Human Rights Commission": 0,
  "National Security Council Secretariat": 0,
  "Office of Principal Scientific Advisor to Government of India": 0,
  "Other Cabinet Committees": 0,
  "PIB Headquarters": 0,
  "PM Speech": 0,
  "President's Secretariat": 0,
  "Prime Minister's Office": 0,
  "Rajya Sabha Secretariat": 0,
  "Special Service and Features": 0,
  "UPSC": 0,
  "Vice President's Secretariat": 0,
};
