MINISTRY_LOGOS_LINKS = {
    "President's Secretariat": "https://upload.wikimedia.org/wikipedia/commons/c/c3/President_Droupadi_Murmu_official_portrait_higher_version.jpg",
    "Vice President's Secretariat": "https://upload.wikimedia.org/wikipedia/commons/8/8d/Vice_President_Shri_Jagdeep_Dhankar.jpg",
    "Prime Minister's Office": "https://upload.wikimedia.org/wikipedia/commons/c/c4/Official_Photograph_of_Prime_Minister_Narendra_Modi_Portrait.png",
    "Lok Sabha Secretariat": "https://upload.wikimedia.org/wikipedia/commons/d/db/View_of_Lok_Sabha_chamber_in_the_New_Parliament_building%2C_New_Delhi.jpg",
    "Rajya Sabha Secretariat": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/New_Rajya_Sabha_chamber_in_the_New_Parliament_building.jpg/330px-New_Rajya_Sabha_chamber_in_the_New_Parliament_building.jpg",
    "Cabinet": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Modi_3.0_Ministry.jpg",
    "Cabinet Committee Decisions": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Modi_3.0_Ministry.jpg",
    "Cabinet Committee on Economic Affairs (CCEA)": "https://gkshortnotes.in/wp-content/uploads/2025/03/images-5.jpeg",
    "Cabinet Secretariat": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Modi_3.0_Ministry.jpg",
    "Cabinet Committee on Infrastructure": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Modi_3.0_Ministry.jpg",
    "Cabinet Committee on Price": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Modi_3.0_Ministry.jpg",
    "Cabinet Committee on Investment": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Modi_3.0_Ministry.jpg",
    "AYUSH": "https://commons.wikimedia.org/wiki/Special:FilePath/Logo_Ministry_of_AYUSH.png",
    "Other Cabinet Committees": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Modi_3.0_Ministry.jpg",
    "Department of Space": "https://upload.wikimedia.org/wikipedia/hi/8/8d/Department_of_Space_logo.png",
    "Department of Ocean Development": "https://commons.wikimedia.org/wiki/Special:FilePath/Emblem_of_India.svg",
    "Department of Atomic Energy": "https://commons.wikimedia.org/wiki/Special:FilePath/Emblem_of_India.svg",
    "Election Commission": "https://commons.wikimedia.org/wiki/Special:FilePath/Election_Commission_of_India_Logo.svg",
    "Finance Commission": "https://commons.wikimedia.org/wiki/Special:FilePath/Emblem_of_India.svg",
    "Ministry of Agriculture & Farmers Welfare": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Agriculture_India.svg",
    "Ministry of Agro & Rural Industries": "https://commons.wikimedia.org/wiki/Special:FilePath/Emblem_of_India.svg",
    "Ministry of Chemicals and Fertilizers": "https://commons.wikimedia.org/wiki/Special:FilePath/Emblem_of_India.svg",
    "Ministry of Civil Aviation": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Civil_Aviation_India.svg",
    "Ministry of Coal": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Coal_India.svg",
    "Ministry of Commerce & Industry": "https://commons.wikimedia.org/wiki/Special:FilePath/Emblem_of_India.svg",
    "Ministry of Communications": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Communications_India.svg",
    "Ministry of Company Affairs": "https://commons.wikimedia.org/wiki/Special:FilePath/Emblem_of_India.svg",
    "Ministry of Consumer Affairs, Food & Public Distribution": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Consumer_Affairs%2CFood_and_Public_Distribution.png",
    "Ministry of Cooperation": "https://commons.wikimedia.org/wiki/Special:FilePath/Emblem_of_India.svg",
    "Ministry of Corporate Affairs": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Corporate_Affairs_India.svg",
    "Ministry of Culture": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Culture_India.svg",
    "Ministry of Defence": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Defence_India.svg",
    "Ministry of Development of North-East Region": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Development_of_North_Eastern_Region_India.svg",
    "Ministry of Disinvestment": "https://commons.wikimedia.org/wiki/Special:FilePath/Emblem_of_India.svg",
    "Ministry of Drinking Water & Sanitation": "https://upload.wikimedia.org/wikipedia/commons/5/52/Boy_drinks_from_a_tap_at_a_NEWAH_WASH_water_project_in_Puware_Shikhar%2C_Udayapur_District%2C_Nepal._%2810677936093%29.jpg",
    "Ministry of Earth Sciences": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Earth_Sciences.jpg",
    "Ministry of Education": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Education_India.svg",
    "Ministry of Electronics & IT": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Electronics_and_Information_Technology.svg",
    "Ministry of Environment, Forest and Climate Change": "https://commons.wikimedia.org/wiki/Special:FilePath/Emblem_of_India.svg",
    "Ministry of External Affairs": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_External_Affairs_India.svg",
    "Ministry of Finance": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Finance_India.svg",
    "Ministry of Fisheries, Animal Husbandry & Dairying": "https://commons.wikimedia.org/wiki/Special:FilePath/Logo_of_Ministry_of_Fisheries%2C_Animal_Husbandry_and_Dairying.png",
    "Ministry of Food Processing Industries": "https://commons.wikimedia.org/wiki/Special:FilePath/Emblem_of_India.svg",
    "Ministry of Health and Family Welfare": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Health_India.svg",
    "Ministry of Heavy Industries": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Heavy_Industries_India.svg",
    "Ministry of Home Affairs": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Home_Affairs_India.svg",
    "Ministry of Housing & Urban Affairs": "https://commons.wikimedia.org/wiki/Special:FilePath/Emblem_of_India.svg",
    "Ministry of Information & Broadcasting": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Information_and_Broadcasting.svg",
    "Ministry of Jal Shakti": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Jal_Shakti.svg",
    "Ministry of Labour & Employment": "https://commons.wikimedia.org/wiki/Special:FilePath/Emblem_of_India.svg",
    "Ministry of Law and Justice": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Law_and_Justice.png",
    "Ministry of Micro, Small & Medium Enterprises": "https://commons.wikimedia.org/wiki/Special:FilePath/MSME_Logo_India.svg",
    "Ministry of Mines": "https://commons.wikimedia.org/wiki/Special:FilePath/Emblem_of_India.svg",
    "Ministry of Minority Affairs": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Minority_Affairs.svg",
    "Ministry of New and Renewable Energy": "https://commons.wikimedia.org/wiki/Special:FilePath/MNRE_India.svg",
    "Ministry of Overseas Indian Affairs": "https://commons.wikimedia.org/wiki/Special:FilePath/Emblem_of_India.svg",
    "Ministry of Panchayati Raj": "https://commons.wikimedia.org/wiki/Special:FilePath/Emblem_of_India.svg",
    "Ministry of Parliamentary Affairs": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Parliamentary_Affairs_India.png",
    "Ministry of Personnel, Public Grievances & Pensions": "https://commons.wikimedia.org/wiki/Special:FilePath/Emblem_of_India.svg",
    "Ministry of Petroleum & Natural Gas": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Petroleum_India.svg",
    "Ministry of Planning": "https://commons.wikimedia.org/wiki/Special:FilePath/Emblem_of_India.svg",
    "Ministry of Power": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Power_India.svg",
    "Ministry of Railways": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Railways_India.svg",
    "Ministry of Road Transport & Highways": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Road_Transport_and_Highways.svg",
    "Ministry of Rural Development": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Rural_Development.png",
    "Ministry of Science & Technology": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Science_and_Technology_India.svg",
    "Ministry of Ports, Shipping and Waterways": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Ports_Shipping_and_Waterways.svg",
    "Ministry of Skill Development and Entrepreneurship": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Skill_Development_and_Entrepreneurship.svg",
    "Ministry of Social Justice & Empowerment": "https://upload.wikimedia.org/wikipedia/commons/6/66/Ministry_of_Social_Justice_and_Empowerment.png",
    "Ministry of Statistics & Programme Implementation": "https://upload.wikimedia.org/wikipedia/commons/0/09/Ministry_of_Statistics_%26_Programme_Implementation_%28India%29.png",
    "Ministry of Steel": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Steel_India.svg",
    "Ministry of Surface Transport": "https://upload.wikimedia.org/wikipedia/commons/4/4d/Shri_Nitin_Gadkari_on_March_3%2C_2023_%28cropped%29.jpg",
    "Ministry of Textiles": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Textiles_India.svg",
    "Ministry of Tourism": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Tourism_India.svg",
    "Ministry of Tribal Affairs": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Tribal_Affairs.svg",
    "Ministry of Urban Development": "https://commons.wikimedia.org/wiki/Special:FilePath/Emblem_of_India.svg",
    "Ministry of Water Resources, River Development and Ganga Rejuvenation": "https://upload.wikimedia.org/wikipedia/commons/b/b9/Varanasiganga.jpg",
    "Ministry of Women and Child Development": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Women_and_Child_Development_India.svg",
    "Ministry of Youth Affairs and Sports": "https://commons.wikimedia.org/wiki/Special:FilePath/Ministry_of_Youth_Affairs_and_Sports_India.svg",
    "NITI Aayog": "https://upload.wikimedia.org/wikipedia/en/9/95/NITI_Aayog_logo.svg",
    "PM Speech": "https://commons.wikimedia.org/wiki/Special:FilePath/PMO_India_Logo.svg",
    "EAC-PM": "https://commons.wikimedia.org/wiki/Special:FilePath/Emblem_of_India.svg",
    "UPSC": "https://upload.wikimedia.org/wikipedia/commons/3/3d/Drishti_IAS_Logo.png",
    "Special Service and Features": "https://upload.wikimedia.org/wikipedia/commons/6/68/Special_Service_Medal_%28India%29.png",
    "PIB Headquarters": "https://upload.wikimedia.org/wikipedia/commons/b/bd/Press_Information_Bureau%2C_Government_of_India.jpg",
    "Office of Principal Scientific Advisor to Government of India": "https://upload.wikimedia.org/wikipedia/commons/e/ee/K_VijayRhagavan.jpg",
    "National Financial Reporting Authority": "https://commons.wikimedia.org/wiki/Special:FilePath/Emblem_of_India.svg",
    "Competition Commission of India": "https://upload.wikimedia.org/wikipedia/commons/9/96/Logo_of_the_Competition_Commission_of_India.svg",
    "IFSC Authority": "https://bl-i.thgim.com/public/incoming/sqoc24/article68590323.ece/alternates/LANDSCAPE_1200/ifsca.jpg",
    "National Security Council Secretariat": "https://upload.wikimedia.org/wikipedia/commons/6/63/Ajit_Kumar_Doval.jpg",
    "National Human Rights Commission": "https://upload.wikimedia.org/wikipedia/commons/f/f9/NHRC.jpg",
    "Lokpal of India": "https://upload.wikimedia.org/wikipedia/en/0/03/Logo_of_the_Lokpal.jpg"
}
