// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7keRwlDlpZIDV9w2-5Qf7bmZGr8kjGOA',
    appId: '1:49447215056:web:60b113f58fecfaab4ce3d5',
    messagingSenderId: '49447215056',
    projectId: 'se-app-dev-9e20f',
    authDomain: 'se-app-dev-9e20f.firebaseapp.com',
    storageBucket: 'se-app-dev-9e20f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFVmJJxRPS1RaZaY6ipXS4cS1J-pGpaLU',
    appId: '1:49447215056:android:a1a098381f5d8d004ce3d5',
    messagingSenderId: '49447215056',
    projectId: 'se-app-dev-9e20f',
    storageBucket: 'se-app-dev-9e20f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqgKfPxMXuKm-AQ6z6GQLRyZv-yh7wfzw',
    appId: '1:49447215056:ios:b76a57291e0820f44ce3d5',
    messagingSenderId: '49447215056',
    projectId: 'se-app-dev-9e20f',
    storageBucket: 'se-app-dev-9e20f.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqgKfPxMXuKm-AQ6z6GQLRyZv-yh7wfzw',
    appId: '1:49447215056:ios:b76a57291e0820f44ce3d5',
    messagingSenderId: '49447215056',
    projectId: 'se-app-dev-9e20f',
    storageBucket: 'se-app-dev-9e20f.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7keRwlDlpZIDV9w2-5Qf7bmZGr8kjGOA',
    appId: '1:49447215056:web:1ff1857e9d2534154ce3d5',
    messagingSenderId: '49447215056',
    projectId: 'se-app-dev-9e20f',
    authDomain: 'se-app-dev-9e20f.firebaseapp.com',
    storageBucket: 'se-app-dev-9e20f.firebasestorage.app',
  );
}
